// AUTO-GENERATED by scripts/walkthroughs/episode.ts
export default {
  "episodeId": "noderoom-proof-release-v1",
  "fps": 30,
  "title": "NodeRoom proof release: working product, measured limits, reproducible receipts",
  "scenes": [
    {
      "id": "premise",
      "kind": "card",
      "video": null,
      "images": [],
      "audio": "audio/premise.mp3",
      "code": null,
      "durationInFrames": 249,
      "narration": "We tested real deck, notebook, graph, and chat states against every declared benchmark task.",
      "card": {
        "title": "Did NodeRoom prove real product behavior and run the full declared benchmark denominator?",
        "bullets": [
          "product state + benchmark receipts",
          "coverage is not a pass claim"
        ]
      }
    },
    {
      "id": "product-proof",
      "kind": "image",
      "video": null,
      "images": [
        "image/product-proof-0.png",
        "image/product-proof-1.png",
        "image/product-proof-2.png",
        "image/product-proof-3.png"
      ],
      "audio": "audio/product-proof.mp3",
      "code": null,
      "durationInFrames": 303,
      "narration": "Deck saves, notebook kernels, draggable graph clusters, and scoped chat references all run through real product paths.",
      "card": {
        "title": "Do the new work-artifact interiors perform real actions?",
        "bullets": []
      }
    },
    {
      "id": "denominator",
      "kind": "card",
      "video": null,
      "images": [],
      "audio": "audio/denominator.mp3",
      "code": null,
      "durationInFrames": 369,
      "narration": "The strict ledger executes 1,739 of 1,739 staged tasks, including every SpreadsheetBench track.",
      "card": {
        "title": "Was the full declared task set executed?",
        "bullets": [
          "SpreadsheetBench V1: 912/912",
          "Verified400: 400/400",
          "SpreadsheetBench V2: 321/321"
        ]
      }
    },
    {
      "id": "conflict",
      "kind": "card",
      "video": null,
      "images": [],
      "audio": "audio/conflict.mp3",
      "code": null,
      "durationInFrames": 330,
      "narration": "Coverage exposed weak quality: V1 passed 89 of 912; V2 passed zero of 321.",
      "card": {
        "title": "Did full execution translate into strong performance?",
        "bullets": []
      }
    },
    {
      "id": "fixes",
      "kind": "code",
      "video": null,
      "images": [],
      "audio": "audio/fixes.mp3",
      "code": {
        "title": "Finch regeneration safety",
        "lines": [
          "export function resetFinchModelOutputBaseline(args: {",
          "  outputRoot: string;",
          "  modelOutputDir: string;",
          "  modelOutputManifestPath: string;",
          "}): void {",
          "  mkdirSync(args.outputRoot, { recursive: true });",
          "  rmSync(args.modelOutputDir, { recursive: true, force: true });",
          "  rmSync(args.modelOutputManifestPath, { force: true });",
          "}",
          "",
          "export function shouldPreserveOfficialScoreClaim(args: {"
        ]
      },
      "durationInFrames": 321,
      "narration": "Failures drove exact resume, parser, cost, transport, and non-destructive scorer-input fixes, each locked by tests.",
      "card": {
        "title": "Finch regeneration safety",
        "bullets": [
          "preserve rendered eval_set",
          "revalidate before retaining a claim"
        ]
      }
    },
    {
      "id": "external-scorers",
      "kind": "card",
      "video": null,
      "images": [],
      "audio": "audio/external-scorers.mp3",
      "code": null,
      "durationInFrames": 321,
      "narration": "FinAuditing, MBABench, and canonical Finch are accepted. Free-router votes remain non-promotable shadow evidence.",
      "card": {
        "title": "Which external score claims have accepted upstream receipts?",
        "bullets": [
          "Finch: 172/172 canonical judge",
          "direct OpenAI, no Azure resource",
          "free router cannot promote"
        ]
      }
    },
    {
      "id": "gate",
      "kind": "card",
      "video": null,
      "images": [],
      "audio": "audio/gate.mp3",
      "code": null,
      "durationInFrames": 330,
      "narration": "The current gate passes: seventeen required tasks, zero blocked, accepted receipts, and repository validation.",
      "card": {
        "title": "May this be posted as a completed certification release?",
        "bullets": [
          "17/17 required goal tasks",
          "0 blocked tasks",
          "README generated from receipts"
        ]
      }
    }
  ],
  "totalFrames": 2223,
  "music": "audio/bed.mp3"
};
