// AUTO-GENERATED by scripts/walkthroughs/episode.ts
export default {
  "episodeId": "stack-before-after-v1",
  "fps": 30,
  "title": "I Built It on Streamlit First. Then the Demo Needed a Second User.",
  "scenes": [
    {
      "id": "cold-open",
      "kind": "video",
      "video": "video/cold-open.mp4",
      "audio": "audio/cold-open.mp3",
      "code": null,
      "durationInFrames": 330,
      "narration": "I built the research workflow on Streamlit first. Single player, it's excellent — paste a list, run the pipeline, score the companies.",
      "card": {
        "title": "cold-open",
        "bullets": []
      }
    },
    {
      "id": "structural-stop",
      "kind": "card",
      "video": null,
      "audio": "audio/structural-stop.mp3",
      "code": null,
      "durationInFrames": 312,
      "narration": "Then the demo needed a second user. Nothing was broken — a typical stack just doesn't hold live, shared, versioned state. By construction.",
      "card": {
        "title": "Where typical stacks stop — by construction, not by fault",
        "bullets": [
          "no presence — one person at a time",
          "no shared versions — last write wins",
          "no review lane for an agent's changes"
        ]
      }
    },
    {
      "id": "after-room",
      "kind": "video",
      "video": "video/after-room.mp4",
      "audio": "audio/after-room.mp3",
      "code": null,
      "durationInFrames": 330,
      "narration": "The same workflow in a live room: owners, status, and every change attributed and versioned.",
      "card": {
        "title": "after-room",
        "bullets": []
      }
    },
    {
      "id": "after-review",
      "kind": "video",
      "video": "video/after-review.mp4",
      "audio": "audio/after-review.mp3",
      "code": null,
      "durationInFrames": 288,
      "narration": "And the agent proposes instead of overwrites — you approve right where the change lands.",
      "card": {
        "title": "after-review",
        "bullets": []
      }
    },
    {
      "id": "closing",
      "kind": "card",
      "video": null,
      "audio": "audio/closing.mp3",
      "code": null,
      "durationInFrames": 246,
      "narration": "Same feature, two stacks. The difference isn't intelligence — it's the collaboration substrate underneath.",
      "card": {
        "title": "Not a rewrite of Streamlit — the layer it never claimed to be",
        "bullets": [
          "live shared state across people and agents",
          "every edit versioned, every change attributed",
          "agent writes reviewable before they count"
        ]
      }
    }
  ],
  "totalFrames": 1506
};
