/**
 * Episode composition — the 60-second vertical short (1080×1920), assembled from LIVE walkthrough
 * MP4s + real ElevenLabs narration + honest claim-cards for staged scenes. Sequenced per
 * remotion/episode.data.js (generated by scripts/walkthroughs/episode.ts).
 * Style: quiet competence — dark, calm, one accent; narration text doubles as the caption.
 */
import React from "react";
import { AbsoluteFill, Audio, OffthreadVideo, Sequence, interpolate, staticFile, useCurrentFrame } from "remotion";

export const EP_FPS = 30;
const W = 1080, H = 1920;
const ACCENT = "#D97757";
const FONT = '"Inter", "Segoe UI", system-ui, -apple-system, sans-serif';

type EpScene = { id: string; kind: "video" | "card"; video: string | null; audio: string | null; durationInFrames: number; narration: string; card: { title: string; bullets: string[] } };
export type EpisodeData = { episodeId: string; fps: number; title: string; scenes: EpScene[]; totalFrames: number };

const VIDEO_W = 1000;
const VIDEO_H = Math.round(VIDEO_W * 848 / 1280); // captures are 1280×848

const Card: React.FC<{ scene: EpScene; f: number }> = ({ scene, f }) => {
  const inT = (d: number) => interpolate(Math.max(0, f - d), [0, 10], [0, 1], { extrapolateRight: "clamp" });
  return (
    <div style={{ width: VIDEO_W, minHeight: VIDEO_H, borderRadius: 22, background: "linear-gradient(165deg,#161b22,#0d1117)", border: "1px solid rgba(255,255,255,.09)", padding: "70px 64px", display: "flex", flexDirection: "column", justifyContent: "center", gap: 40, boxShadow: "0 40px 90px rgba(0,0,0,.6)" }}>
      <div style={{ fontFamily: FONT, fontSize: 46, fontWeight: 800, color: "#f2f4f7", letterSpacing: "-.01em", opacity: inT(0) }}>{scene.card.title}</div>
      {scene.card.bullets.map((b, i) => (
        <div key={b} style={{ display: "flex", alignItems: "center", gap: 22, opacity: inT(6 + i * 5) }}>
          <span style={{ flex: "none", width: 14, height: 14, borderRadius: 7, background: ACCENT }} />
          <span style={{ fontFamily: FONT, fontSize: 34, fontWeight: 600, color: "#c6ccd4", lineHeight: 1.35 }}>{b}</span>
        </div>
      ))}
    </div>
  );
};

export const Episode: React.FC<{ data: EpisodeData }> = ({ data }) => {
  const frame = useCurrentFrame();
  let acc = 0;
  const starts = data.scenes.map((s) => { const x = acc; acc += s.durationInFrames; return x; });
  const progress = Math.min(1, frame / data.totalFrames);

  return (
    <AbsoluteFill style={{ background: "radial-gradient(1100px 800px at 50% -10%, #182030 0%, #0b0f16 55%, #07090d 100%)", fontFamily: FONT }}>
      {/* header */}
      <div style={{ position: "absolute", top: 90, left: 70, right: 70 }}>
        <div style={{ fontSize: 26, fontWeight: 800, letterSpacing: ".14em", color: ACCENT, textTransform: "uppercase" }}>NodeRoom · noderoom.live</div>
        <div style={{ marginTop: 16, fontSize: 40, fontWeight: 800, color: "#f2f4f7", lineHeight: 1.22, letterSpacing: "-.015em" }}>{data.title}</div>
      </div>

      {data.scenes.map((s, i) => {
        const local = frame - starts[i];
        return (
          <Sequence key={s.id} from={starts[i]} durationInFrames={s.durationInFrames}>
            {s.audio && <Audio src={staticFile(s.audio)} />}
            {/* center stage */}
            <AbsoluteFill style={{ justifyContent: "center", alignItems: "center" }}>
              <div style={{ opacity: interpolate(local, [0, 8], [0, 1], { extrapolateRight: "clamp" }) }}>
                {s.kind === "video" && s.video ? (
                  <div style={{ width: VIDEO_W, height: VIDEO_H, borderRadius: 22, overflow: "hidden", boxShadow: "0 40px 90px rgba(0,0,0,.65), 0 0 0 1px rgba(255,255,255,.08)" }}>
                    <OffthreadVideo src={staticFile(s.video)} muted style={{ width: VIDEO_W, height: VIDEO_H }} />
                  </div>
                ) : (
                  <Card scene={s} f={Math.max(0, local)} />
                )}
              </div>
            </AbsoluteFill>
            {/* narration caption */}
            <AbsoluteFill style={{ justifyContent: "flex-end", alignItems: "center", paddingBottom: 200, pointerEvents: "none" }}>
              <div style={{ maxWidth: 920, background: "rgba(8,11,16,.84)", border: "1px solid rgba(255,255,255,.12)", borderRadius: 18, padding: "26px 38px", opacity: interpolate(local, [2, 9], [0, 1], { extrapolateRight: "clamp" }) }}>
                <div style={{ fontSize: 34, fontWeight: 650, color: "#eef2f7", lineHeight: 1.4, textAlign: "center" }}>{s.narration}</div>
              </div>
            </AbsoluteFill>
          </Sequence>
        );
      })}

      {/* progress */}
      <div style={{ position: "absolute", bottom: 0, left: 0, height: 10, width: W * progress, background: ACCENT }} />
      <div style={{ position: "absolute", bottom: 60, left: 0, right: 0, textAlign: "center", fontSize: 24, fontWeight: 600, color: "#66717c" }}>
        rendered from the repo · github.com/HomenShum/noderoom
      </div>
    </AbsoluteFill>
  );
};

export const EP_SIZE = { width: W, height: H };
