/**
 * Episode composition — the 60-second vertical short (1080×1920), assembled from LIVE walkthrough
 * MP4s + real ElevenLabs narration + honest claim-cards for staged scenes. Sequenced per
 * remotion/episode.data.js (generated by scripts/walkthroughs/episode.ts).
 * Style: quiet competence — dark, calm, one accent; narration text doubles as the caption.
 */
import React from "react";
import { AbsoluteFill, Audio, OffthreadVideo, Sequence, interpolate, staticFile, useCurrentFrame } from "remotion";

export const EP_FPS = 30;
const W = 1080, H = 1920;
const ACCENT = "#D97757";
const FONT = '"Inter", "Segoe UI", system-ui, -apple-system, sans-serif';

type EpScene = {
  id: string; kind: "video" | "card" | "code" | "diagram"; video: string | null; audio: string | null;
  code?: { title: string; lines: string[] } | null;
  durationInFrames: number; narration: string; card: { title: string; bullets: string[] };
};
export type EpisodeData = { episodeId: string; fps: number; title: string; scenes: EpScene[]; totalFrames: number };

const VIDEO_W = 1000;
const VIDEO_H = Math.round(VIDEO_W * 848 / 1280); // captures are 1280×848

function videoScale(sceneId: string): number {
  if (sceneId === "continuity") return 1.18;
  if (sceneId === "cold-open" || sceneId === "provenance" || sceneId === "after-room" || sceneId === "after-review") return 1.08;
  return 1;
}

const Card: React.FC<{ scene: EpScene; f: number }> = ({ scene, f }) => {
  const inT = (d: number) => interpolate(Math.max(0, f - d), [0, 10], [0, 1], { extrapolateRight: "clamp" });
  return (
    <div style={{ width: VIDEO_W, minHeight: VIDEO_H, borderRadius: 22, background: "linear-gradient(165deg,#161b22,#0d1117)", border: "1px solid rgba(255,255,255,.09)", padding: "70px 64px", display: "flex", flexDirection: "column", justifyContent: "center", gap: 40, boxShadow: "0 40px 90px rgba(0,0,0,.6)" }}>
      <div style={{ fontFamily: FONT, fontSize: 46, fontWeight: 800, color: "#f2f4f7", letterSpacing: "-.01em", opacity: inT(0) }}>{scene.card.title}</div>
      {scene.card.bullets.map((b, i) => (
        <div key={b} style={{ display: "flex", alignItems: "center", gap: 22, opacity: inT(6 + i * 5) }}>
          <span style={{ flex: "none", width: 14, height: 14, borderRadius: 7, background: ACCENT }} />
          <span style={{ fontFamily: FONT, fontSize: 34, fontWeight: 600, color: "#c6ccd4", lineHeight: 1.35 }}>{b}</span>
        </div>
      ))}
    </div>
  );
};

/** Real code from the repo, revealed line by line — the viewer sees the actual guard, not bullets
 *  claiming it exists. Lines are extracted at assemble time so they can never drift from the repo. */
const CodePanel: React.FC<{ scene: EpScene; f: number }> = ({ scene, f }) => {
  const lines = scene.code?.lines ?? [];
  const shown = Math.min(lines.length, Math.floor(f / 2) + 1); // ~15 lines/sec reveal
  return (
    <div style={{ width: VIDEO_W, borderRadius: 22, background: "#0d1117", border: "1px solid rgba(255,255,255,.09)", boxShadow: "0 40px 90px rgba(0,0,0,.6)", overflow: "hidden" }}>
      <div style={{ padding: "18px 28px", borderBottom: "1px solid rgba(255,255,255,.08)", fontFamily: FONT, fontSize: 24, fontWeight: 700, color: ACCENT }}>{scene.code?.title}</div>
      <div style={{ padding: "22px 28px", fontFamily: '"JetBrains Mono", Consolas, monospace', fontSize: 19.5, lineHeight: 1.5 }}>
        {lines.slice(0, shown).map((l, i) => {
          const hot = /LOCK|conflict|pending_approval|version|CAS|lease/i.test(l);
          return <div key={i} style={{ color: hot ? "#f2c197" : l.trim().startsWith("//") ? "#5b6775" : "#aeb8c4", whiteSpace: "pre", overflow: "hidden", textOverflow: "ellipsis" }}>{l || " "}</div>;
        })}
      </div>
      <div style={{ display: "flex", gap: 12, flexWrap: "wrap", padding: "0 28px 22px" }}>
        {scene.card.bullets.map((b, i) => (
          <span key={b} style={{ fontFamily: FONT, fontSize: 20, fontWeight: 650, color: "#eef2f7", background: "rgba(217,119,87,.16)", border: `1px solid ${ACCENT}55`, borderRadius: 10, padding: "8px 14px", opacity: interpolate(f - 20 - i * 8, [0, 8], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }) }}>{b}</span>
        ))}
      </div>
    </div>
  );
};

/** Animated mental-model diagram: a human and an agent reach for the same cell; the room turns the
 *  collision into lock → draft → review → merge instead of a clobber. Plain shapes, staged reveal. */
const Diagram: React.FC<{ f: number }> = ({ f }) => {
  const at = (start: number, dur = 10) => interpolate(f - start, [0, dur], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const Box: React.FC<{ x: number; y: number; w: number; label: string; sub?: string; color: string; t: number }> = ({ x, y, w, label, sub, color, t }) => (
    <div style={{ position: "absolute", left: x, top: y + (1 - t) * 14, width: w, opacity: t, background: "#161b22", border: `2px solid ${color}`, borderRadius: 14, padding: "14px 18px", textAlign: "center" }}>
      <div style={{ fontFamily: FONT, fontSize: 24, fontWeight: 750, color: "#f2f4f7" }}>{label}</div>
      {sub && <div style={{ fontFamily: FONT, fontSize: 17, color: "#99a3ae", marginTop: 4 }}>{sub}</div>}
    </div>
  );
  const Arrow: React.FC<{ x1: number; y1: number; x2: number; y2: number; t: number; color?: string }> = ({ x1, y1, x2, y2, t, color = "#66717c" }) => (
    <svg style={{ position: "absolute", left: 0, top: 0, pointerEvents: "none" }} width={VIDEO_W} height={620}>
      <line x1={x1} y1={y1} x2={x1 + (x2 - x1) * t} y2={y1 + (y2 - y1) * t} stroke={color} strokeWidth={3.5} strokeLinecap="round" />
      {t > 0.95 && <circle cx={x2} cy={y2} r={6} fill={color} />}
    </svg>
  );
  return (
    <div style={{ position: "relative", width: VIDEO_W, height: 620, borderRadius: 22, background: "linear-gradient(165deg,#141a23,#0c1016)", border: "1px solid rgba(255,255,255,.09)", boxShadow: "0 40px 90px rgba(0,0,0,.6)" }}>
      <Box x={70} y={50} w={250} label="Human" sub="edits cell C4" color="#5b9bf5" t={at(0)} />
      <Box x={680} y={50} w={250} label="Agent" sub="wants C4 too" color={ACCENT} t={at(8)} />
      <Box x={375} y={230} w={250} label="The cell" sub="one shared version" color="#7bd089" t={at(16)} />
      <Arrow x1={195} y1={140} x2={460} y2={228} t={at(24)} color="#5b9bf5" />
      <Arrow x1={805} y1={140} x2={540} y2={228} t={at(30)} color={ACCENT} />
      <Box x={70} y={420} w={262} label="Lock" sub="agent claims the range" color={ACCENT} t={at(40)} />
      <Box x={375} y={420} w={250} label="Draft" sub="blocked write waits" color="#e4c567" t={at(50)} />
      <Box x={680} y={420} w={262} label="Review → merge" sub="human approves, nothing lost" color="#7bd089" t={at(60)} />
      <Arrow x1={332} y1={455} x2={373} y2={455} t={at(48, 6)} />
      <Arrow x1={627} y1={455} x2={678} y2={455} t={at(58, 6)} />
    </div>
  );
};

export const Episode: React.FC<{ data: EpisodeData }> = ({ data }) => {
  const frame = useCurrentFrame();
  let acc = 0;
  const starts = data.scenes.map((s) => { const x = acc; acc += s.durationInFrames; return x; });
  const progress = Math.min(1, frame / data.totalFrames);

  return (
    <AbsoluteFill style={{ background: "radial-gradient(1100px 800px at 50% -10%, #182030 0%, #0b0f16 55%, #07090d 100%)", fontFamily: FONT }}>
      {/* header */}
      <div style={{ position: "absolute", top: 90, left: 70, right: 70 }}>
        <div style={{ fontSize: 26, fontWeight: 800, letterSpacing: ".14em", color: ACCENT, textTransform: "uppercase" }}>NodeRoom · noderoom.live</div>
        <div style={{ marginTop: 16, fontSize: 40, fontWeight: 800, color: "#f2f4f7", lineHeight: 1.22, letterSpacing: "-.015em" }}>{data.title}</div>
      </div>

      {data.scenes.map((s, i) => {
        const local = frame - starts[i];
        return (
          <Sequence key={s.id} from={starts[i]} durationInFrames={s.durationInFrames}>
            {s.audio && <Audio src={staticFile(s.audio)} />}
            {/* center stage */}
            <AbsoluteFill style={{ justifyContent: "center", alignItems: "center" }}>
              <div style={{ opacity: interpolate(local, [0, 8], [0, 1], { extrapolateRight: "clamp" }) }}>
                {s.kind === "video" && s.video ? (
                  <div style={{ width: VIDEO_W, height: VIDEO_H, borderRadius: 22, overflow: "hidden", boxShadow: "0 40px 90px rgba(0,0,0,.65), 0 0 0 1px rgba(255,255,255,.08)" }}>
                    <OffthreadVideo src={staticFile(s.video)} muted style={{ width: VIDEO_W, height: VIDEO_H, transform: `scale(${videoScale(s.id)})`, transformOrigin: "50% 48%" }} />
                  </div>
                ) : s.kind === "code" && s.code?.lines?.length ? (
                  <CodePanel scene={s} f={Math.max(0, local)} />
                ) : s.kind === "diagram" ? (
                  <Diagram f={Math.max(0, local)} />
                ) : (
                  <Card scene={s} f={Math.max(0, local)} />
                )}
              </div>
            </AbsoluteFill>
            {/* narration caption */}
            <AbsoluteFill style={{ justifyContent: "flex-end", alignItems: "center", paddingBottom: 200, pointerEvents: "none" }}>
              <div style={{ maxWidth: 920, background: "rgba(8,11,16,.84)", border: "1px solid rgba(255,255,255,.12)", borderRadius: 18, padding: "26px 38px", opacity: interpolate(local, [2, 9], [0, 1], { extrapolateRight: "clamp" }) }}>
                <div style={{ fontSize: 34, fontWeight: 650, color: "#eef2f7", lineHeight: 1.4, textAlign: "center" }}>{s.narration}</div>
              </div>
            </AbsoluteFill>
          </Sequence>
        );
      })}

      {/* progress */}
      <div style={{ position: "absolute", bottom: 0, left: 0, height: 10, width: W * progress, background: ACCENT }} />
      <div style={{ position: "absolute", bottom: 60, left: 0, right: 0, textAlign: "center", fontSize: 24, fontWeight: 600, color: "#66717c" }}>
        rendered from the repo · github.com/HomenShum/noderoom
      </div>
    </AbsoluteFill>
  );
};

export const EP_SIZE = { width: W, height: H };
