// AUTO-GENERATED by scripts/walkthroughs/episode.ts
export default {
  "episodeId": "noderoom-live-collab-v1",
  "fps": 30,
  "title": "I Tried to Make a Demo GIF for a Spreadsheet Agent. It Turned Into a Multiplayer AI Workspace.",
  "scenes": [
    {
      "id": "cold-open",
      "kind": "video",
      "video": "video/cold-open.mp4",
      "audio": "audio/cold-open.mp3",
      "durationInFrames": 243,
      "narration": "I only wanted a clean README GIF for a spreadsheet agent.",
      "card": {
        "title": "cold-open",
        "bullets": []
      }
    },
    {
      "id": "naive-problem",
      "kind": "video",
      "video": "video/naive-problem.mp4",
      "audio": "audio/naive-problem.mp3",
      "durationInFrames": 300,
      "narration": "But the moment a human and an agent edit the same artifact, the demo stops being simple.",
      "card": {
        "title": "The naive demo breaks",
        "bullets": [
          "Human edits a cell",
          "Agent writes a stale value",
          "Silent overwrite — nobody sees it"
        ]
      }
    },
    {
      "id": "code-before-after",
      "kind": "card",
      "video": null,
      "audio": "audio/code-before-after.mp3",
      "durationInFrames": 162,
      "narration": "The write path stopped assuming the agent owns the latest state.",
      "card": {
        "title": "convex/artifacts.ts — applyCellEditCore",
        "bullets": [
          "affected-range LOCK gate",
          "per-element VERSION check (CAS)",
          "draft / proposal on conflict — never clobber"
        ]
      }
    },
    {
      "id": "mental-model",
      "kind": "card",
      "video": null,
      "audio": "audio/mental-model.mp3",
      "durationInFrames": 162,
      "narration": "Treat the room as a collaboration substrate, not a spreadsheet.",
      "card": {
        "title": "The room is the product",
        "bullets": [
          "lock → draft → smart merge",
          "proposal review at the cell",
          "every edit traced + versioned"
        ]
      }
    },
    {
      "id": "review-mode",
      "kind": "video",
      "video": "video/review-mode.mp4",
      "audio": "audio/review-mode.mp3",
      "durationInFrames": 282,
      "narration": "Don't trust the agent yet? Its writes become proposals you approve at the cell.",
      "card": {
        "title": "review-mode",
        "bullets": []
      }
    },
    {
      "id": "multiplayer-proof",
      "kind": "video",
      "video": "video/multiplayer-proof.mp4",
      "audio": "audio/multiplayer-proof.mp3",
      "durationInFrames": 321,
      "narration": "Two humans and an agent in one room — same-cell edits converge, nobody clobbers anybody.",
      "card": {
        "title": "multiplayer-proof",
        "bullets": []
      }
    },
    {
      "id": "closing-thesis",
      "kind": "card",
      "video": null,
      "audio": "audio/closing-thesis.mp3",
      "durationInFrames": 261,
      "narration": "The agent was not the product. The collaboration substrate was — and this video was rendered from the repo that proves it.",
      "card": {
        "title": "Agents are leaving the chatbox",
        "bullets": [
          "Shared work surfaces need versions, locks, review",
          "This video was rendered from the repo that proves it"
        ]
      }
    }
  ],
  "totalFrames": 1731
};
