// AUTO-GENERATED by scripts/walkthroughs/capture.ts — live-captured walkthrough data.
export default {
  "capturedAt": "2026-06-28T05:15:13.923Z",
  "baseUrl": "http://localhost:5273",
  "viewport": {
    "width": 1280,
    "height": 800
  },
  "features": [
    {
      "id": "chat",
      "title": "Join a live room & chat",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/chat/01.png",
          "caption": "A fresh room — company research, diligence memo, risk wall, and agents",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2000
        },
        {
          "frame": "frames/chat/02.png",
          "caption": "Click the room chat — Slack rules apply",
          "cursor": {
            "x": 1073,
            "y": 518
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/chat/03.png",
          "caption": "Click the room chat — Slack rules apply",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 950
        },
        {
          "frame": "frames/chat/04.png",
          "caption": "Type your message…",
          "cursor": {
            "x": 1073,
            "y": 518
          },
          "click": false,
          "kind": "action",
          "holdMs": 800
        },
        {
          "frame": "frames/chat/05.png",
          "caption": "Type your message…",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 520
        },
        {
          "frame": "frames/chat/06.png",
          "caption": "Type your message…",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 1300
        },
        {
          "frame": "frames/chat/07.png",
          "caption": "Enter sends — it paints instantly, before the network",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1700
        },
        {
          "frame": "frames/chat/08.png",
          "caption": "Everyone in the room sees it in real time",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2200
        }
      ]
    },
    {
      "id": "sheet-undo",
      "title": "Edit the diligence memo — and take it back",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/sheet-undo/01.png",
          "caption": "The diligence memo — a shared note the room can edit",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 1800
        },
        {
          "frame": "frames/sheet-undo/02.png",
          "caption": "Open the diligence memo",
          "cursor": {
            "x": 707,
            "y": 94
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/sheet-undo/03.png",
          "caption": "Open the diligence memo",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 950
        },
        {
          "frame": "frames/sheet-undo/04.png",
          "caption": "Click the note — start typing",
          "cursor": {
            "x": 588,
            "y": 239
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/sheet-undo/05.png",
          "caption": "Click the note — start typing",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 950
        },
        {
          "frame": "frames/sheet-undo/06.png",
          "caption": "Type your notes…",
          "cursor": {
            "x": 588,
            "y": 239
          },
          "click": false,
          "kind": "action",
          "holdMs": 800
        },
        {
          "frame": "frames/sheet-undo/07.png",
          "caption": "Type your notes…",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 520
        },
        {
          "frame": "frames/sheet-undo/08.png",
          "caption": "Type your notes…",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 1300
        },
        {
          "frame": "frames/sheet-undo/09.png",
          "caption": "Changed your mind? Undo (Ctrl+Z) — reverted through the same versioned edit path",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1500
        },
        {
          "frame": "frames/sheet-undo/10.png",
          "caption": "Every edit is CAS-versioned — undo is safe in a multiplayer room",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2200
        }
      ]
    },
    {
      "id": "ask-agent",
      "title": "Ask the Room agent to enrich companies",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/ask-agent/01.png",
          "caption": "CardioNova is pending — ask the agent to enrich with sourced facts",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 1800
        },
        {
          "frame": "frames/ask-agent/02.png",
          "caption": "Agents live in the chat — no separate console",
          "cursor": {
            "x": 1073,
            "y": 518
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/ask-agent/03.png",
          "caption": "Agents live in the chat — no separate console",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 950
        },
        {
          "frame": "frames/ask-agent/04.png",
          "caption": "Plain language — @nodeagent hands the research to the Room NodeAgent",
          "cursor": {
            "x": 1073,
            "y": 518
          },
          "click": false,
          "kind": "action",
          "holdMs": 800
        },
        {
          "frame": "frames/ask-agent/05.png",
          "caption": "Plain language — @nodeagent hands the research to the Room NodeAgent",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 1300
        },
        {
          "frame": "frames/ask-agent/06.png",
          "caption": "The agent reads the sheet, researches, and writes — sourced facts land in the sheet",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2100
        },
        {
          "frame": "frames/ask-agent/07.png",
          "caption": "Every agent step is traced — auditable, never silent",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2400
        }
      ]
    },
    {
      "id": "review-approve",
      "title": "Review mode — approve agent edits at the cell",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/review-approve/01.png",
          "caption": "Don't trust the agent yet? Flip off auto-allow",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 1800
        },
        {
          "frame": "frames/review-approve/02.png",
          "caption": "Review mode ON — agents must propose, not write",
          "cursor": {
            "x": 771,
            "y": 29
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/review-approve/03.png",
          "caption": "Review mode ON — agents must propose, not write",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 950
        },
        {
          "frame": "frames/review-approve/04.png",
          "caption": "Same ask — but now every edit needs your sign-off",
          "cursor": {
            "x": 1073,
            "y": 518
          },
          "click": false,
          "kind": "action",
          "holdMs": 800
        },
        {
          "frame": "frames/review-approve/05.png",
          "caption": "Same ask — but now every edit needs your sign-off",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 520
        },
        {
          "frame": "frames/review-approve/06.png",
          "caption": "Same ask — but now every edit needs your sign-off",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 1300
        },
        {
          "frame": "frames/review-approve/07.png",
          "caption": "The agent works — proposals appear as reviewable cards",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2100
        },
        {
          "frame": "frames/review-approve/08.png",
          "caption": "Approve right where the change lands",
          "cursor": {
            "x": 305,
            "y": 466
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/review-approve/09.png",
          "caption": "Applied via the same no-clobber CAS path — synced to everyone",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1700
        },
        {
          "frame": "frames/review-approve/10.png",
          "caption": "Human-in-the-loop, one click, in context",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2400
        }
      ]
    },
    {
      "id": "room-home",
      "title": "Room Home — the pinned command center",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/room-home/01.png",
          "caption": "A populated deal room — artifacts open as tabs",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2000
        },
        {
          "frame": "frames/room-home/02.png",
          "caption": "A pinned Home tab — always one click away",
          "cursor": {
            "x": 253,
            "y": 94
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/room-home/03.png",
          "caption": "Room Home: command bar, inventory, and quick actions",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1700
        },
        {
          "frame": "frames/room-home/04.png",
          "caption": "The full inventory — every artifact, even unopened ones",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2200
        },
        {
          "frame": "frames/room-home/05.png",
          "caption": "Dive into any artifact",
          "cursor": {
            "x": 732,
            "y": 375
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/room-home/06.png",
          "caption": "It opens as a tab — Home steps aside",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1700
        },
        {
          "frame": "frames/room-home/07.png",
          "caption": "Your command center, never buried in tabs",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2400
        }
      ]
    }
  ]
};
