// AUTO-GENERATED by scripts/walkthroughs/capture.ts — live-captured walkthrough data.
export default {
  "capturedAt": "2026-06-22T05:33:03.204Z",
  "baseUrl": "https://noderoom.vercel.app",
  "viewport": {
    "width": 1280,
    "height": 800
  },
  "features": [
    {
      "id": "room-tour-walkthrough",
      "title": "The NodeAgent room walkthrough — 8 steps from landing to live collab",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/room-tour-walkthrough/01.png",
          "caption": "The #room-tour dock walks you through the product — landing, create, join, then the room",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2400
        },
        {
          "frame": "frames/room-tour-walkthrough/02.png",
          "caption": "Step 02 — host a room: a 6-char share code, no account",
          "cursor": {
            "x": 46,
            "y": 771
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/room-tour-walkthrough/03.png",
          "caption": "Anyone with the code can join. The room id is keyed by host.",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2600
        },
        {
          "frame": "frames/room-tour-walkthrough/04.png",
          "caption": "Step 04 — “Enter room” → one panel: public chat + the room agent",
          "cursor": {
            "x": 640,
            "y": 653
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/room-tour-walkthrough/05.png",
          "caption": "Everyone in the room sees the chat. /ask invokes the room agent.",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2400
        },
        {
          "frame": "frames/room-tour-walkthrough/06.png",
          "caption": "Step 05 — open the artifact beside chat",
          "cursor": {
            "x": 85,
            "y": 771
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/room-tour-walkthrough/07.png",
          "caption": "Spreadsheet · Note · Wall — the agent edits the same artifact you do.",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2400
        },
        {
          "frame": "frames/room-tour-walkthrough/08.png",
          "caption": "Step 07 — four panels: navigator · chat · artifact · your private agent",
          "cursor": {
            "x": 111,
            "y": 771
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/room-tour-walkthrough/09.png",
          "caption": "Each panel earns its place. The private agent reads room context, output stays yours.",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2400
        },
        {
          "frame": "frames/room-tour-walkthrough/10.png",
          "caption": "Step 08 — live collab: lock → draft → commit → smart-merge",
          "cursor": {
            "x": 124,
            "y": 771
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/room-tour-walkthrough/11.png",
          "caption": "Two agents, aware of each other. Run the drill.",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1800
        },
        {
          "frame": "frames/room-tour-walkthrough/12.png",
          "caption": "Room agent locks rows it’s about to write; the private agent drafts around the lock",
          "cursor": {
            "x": 847,
            "y": 177
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/room-tour-walkthrough/13.png",
          "caption": "v41 → v43: agent commits Revenue+COGS, smart-merge applies the held Gross profit+Net income draft. No clobber.",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2800
        },
        {
          "frame": "frames/room-tour-walkthrough/14.png",
          "caption": "All eight steps run on scripted seed data — the real product wires the same contracts in Convex",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2400
        }
      ]
    },
    {
      "id": "story-seven-layers",
      "title": "The seven no-clobber layers — a real grid you can drive",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/story-seven-layers/01.png",
          "caption": "The seven-layer story ends in a REAL grid on the in-browser engine",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2200
        },
        {
          "frame": "frames/story-seven-layers/02.png",
          "caption": "Layers 7 + 4 — take a 5-min lease on a cell; NodeAgent drafts around it",
          "cursor": {
            "x": 439,
            "y": 428
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/story-seven-layers/03.png",
          "caption": "Lease blocks the agent's write; it drafts on a neighbor and smart-merges on release",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2800
        },
        {
          "frame": "frames/story-seven-layers/04.png",
          "caption": "Layer 6 — a stale agent write becomes a reviewable semantic-rebase proposal",
          "cursor": {
            "x": 422,
            "y": 428
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/story-seven-layers/05.png",
          "caption": "No silent merge, no clobber — it routes to human review",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2600
        },
        {
          "frame": "frames/story-seven-layers/06.png",
          "caption": "Approve the proposal…",
          "cursor": {
            "x": 390,
            "y": 656
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/story-seven-layers/07.png",
          "caption": "Re-applied at the CURRENT version (v3) — not the stale baseline",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2600
        },
        {
          "frame": "frames/story-seven-layers/08.png",
          "caption": "Layer 5 — stage a stale edit, then run the no-clobber test",
          "cursor": {
            "x": 413,
            "y": 428
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/story-seven-layers/09.png",
          "caption": "Rejected and returned as conflict-as-data — the cell keeps the agent's value",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2800
        },
        {
          "frame": "frames/story-seven-layers/10.png",
          "caption": "Every action hit the real engine — nothing scripted",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2400
        }
      ]
    },
    {
      "id": "chat",
      "title": "Join a live room & chat",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/chat/01.png",
          "caption": "A brand-new room — shared spreadsheet, notes, post-it wall, and agents",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2000
        },
        {
          "frame": "frames/chat/02.png",
          "caption": "Click the room chat — Slack rules apply",
          "cursor": {
            "x": 761,
            "y": 711
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/chat/03.png",
          "caption": "Click the room chat — Slack rules apply",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 950
        },
        {
          "frame": "frames/chat/04.png",
          "caption": "Type your message…",
          "cursor": {
            "x": 761,
            "y": 711
          },
          "click": false,
          "kind": "action",
          "holdMs": 800
        },
        {
          "frame": "frames/chat/05.png",
          "caption": "Type your message…",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 1300
        },
        {
          "frame": "frames/chat/06.png",
          "caption": "Enter sends — it paints instantly, before the network",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1700
        },
        {
          "frame": "frames/chat/07.png",
          "caption": "Everyone in the room sees it in real time",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2200
        }
      ]
    },
    {
      "id": "sheet-undo",
      "title": "Edit the sheet — and take it back",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/sheet-undo/01.png",
          "caption": "The Q3 variance column starts empty",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 1800
        },
        {
          "frame": "frames/sheet-undo/02.png",
          "caption": "Click a cell — Sheets muscle memory",
          "cursor": {
            "x": 1108,
            "y": 362
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/sheet-undo/03.png",
          "caption": "Click a cell — Sheets muscle memory",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 950
        },
        {
          "frame": "frames/sheet-undo/04.png",
          "caption": "Type the variance…",
          "cursor": {
            "x": 1076,
            "y": 379
          },
          "click": false,
          "kind": "action",
          "holdMs": 800
        },
        {
          "frame": "frames/sheet-undo/05.png",
          "caption": "Type the variance…",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 1300
        },
        {
          "frame": "frames/sheet-undo/06.png",
          "caption": "Enter commits — versioned and synced to the whole room",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1700
        },
        {
          "frame": "frames/sheet-undo/07.png",
          "caption": "Changed your mind? Undo (or Ctrl+Z)",
          "cursor": {
            "x": 955,
            "y": 541
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/sheet-undo/08.png",
          "caption": "Reverted through the same versioned edit path — no clobbering",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1700
        },
        {
          "frame": "frames/sheet-undo/09.png",
          "caption": "Every edit is CAS-versioned — undo is safe in a multiplayer room",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2200
        }
      ]
    },
    {
      "id": "workbook-style-toggle",
      "title": "Workbook view modes",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/workbook-style-toggle/01.png",
          "caption": "Start with the shared room; the backend contract is the same for every view",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 1600
        },
        {
          "frame": "frames/workbook-style-toggle/02.png",
          "caption": "Upload a styled Excel workbook",
          "cursor": {
            "x": 140,
            "y": 455
          },
          "click": true,
          "kind": "action",
          "holdMs": 1100
        },
        {
          "frame": "frames/workbook-style-toggle/03.png",
          "caption": "The workbook opens as Excel paper: file formats, merged cells, formula bar, and CAS receipt",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2600
        },
        {
          "frame": "frames/workbook-style-toggle/04.png",
          "caption": "Switch the view to Sheets",
          "cursor": {
            "x": 1086,
            "y": 170
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/workbook-style-toggle/05.png",
          "caption": "Sheets mode keeps the same selected cell and versioned write path",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2800
        },
        {
          "frame": "frames/workbook-style-toggle/06.png",
          "caption": "Switch to Evidence mode for agent review",
          "cursor": {
            "x": 1185,
            "y": 170
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/workbook-style-toggle/07.png",
          "caption": "Evidence mode emphasizes provenance and review without changing data ownership",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 3000
        },
        {
          "frame": "frames/workbook-style-toggle/08.png",
          "caption": "MVP rule: style changes are local UI; Convex versions, locks, and traces stay canonical",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2400
        }
      ]
    },
    {
      "id": "ask-agent",
      "title": "Ask the Room agent to do the work",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/ask-agent/01.png",
          "caption": "Five variance cells to reconcile — ask the agent instead",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 1800
        },
        {
          "frame": "frames/ask-agent/02.png",
          "caption": "Agents live in the chat — no separate console",
          "cursor": {
            "x": 275,
            "y": 690
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/ask-agent/03.png",
          "caption": "Agents live in the chat — no separate console",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 950
        },
        {
          "frame": "frames/ask-agent/04.png",
          "caption": "Plain language — /ask hands the sheet to the Room NodeAgent",
          "cursor": {
            "x": 275,
            "y": 690
          },
          "click": false,
          "kind": "action",
          "holdMs": 800
        },
        {
          "frame": "frames/ask-agent/05.png",
          "caption": "Plain language — /ask hands the sheet to the Room NodeAgent",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 1300
        },
        {
          "frame": "frames/ask-agent/06.png",
          "caption": "The agent reads the sheet, locks cells, and works — live status, no dead spinner",
          "cursor": null,
          "click": false,
          "kind": "loading",
          "holdMs": 1600
        },
        {
          "frame": "frames/ask-agent/07.png",
          "caption": "Cells filled with lock→CAS-safe edits + a summary in chat",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2100
        },
        {
          "frame": "frames/ask-agent/08.png",
          "caption": "Every agent step is traced — auditable, never silent",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2400
        }
      ]
    },
    {
      "id": "multi-agent-workbench",
      "title": "Multi-agent work queue",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/multi-agent-workbench/01.png",
          "caption": "A public-gold workload hits the room: PDF arithmetic, FinanceBench QA, SEC XBRL, and no-clobber proof",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 1800
        },
        {
          "frame": "frames/multi-agent-workbench/02.png",
          "caption": "One burst prompt becomes durable child jobs, not one polluted agent thread",
          "cursor": {
            "x": 620,
            "y": 711
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/multi-agent-workbench/03.png",
          "caption": "One burst prompt becomes durable child jobs, not one polluted agent thread",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 950
        },
        {
          "frame": "frames/multi-agent-workbench/04.png",
          "caption": "Submit the public-gold burst prompt",
          "cursor": {
            "x": 620,
            "y": 711
          },
          "click": false,
          "kind": "action",
          "holdMs": 800
        },
        {
          "frame": "frames/multi-agent-workbench/05.png",
          "caption": "Submit the public-gold burst prompt",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 1300
        },
        {
          "frame": "frames/multi-agent-workbench/06.png",
          "caption": "The workbench fans out TAT-DQA, FinanceBench, and SEC child jobs",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2400
        },
        {
          "frame": "frames/multi-agent-workbench/07.png",
          "caption": "Agents stream source reads and tool receipts concurrently while writes stay batched",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2600
        },
        {
          "frame": "frames/multi-agent-workbench/08.png",
          "caption": "The proof board compares NodeRoom output against exact public gold answers",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 3000
        },
        {
          "frame": "frames/multi-agent-workbench/09.png",
          "caption": "Final proof closes the loop: formula, citation, XBRL facts, and human edit preserved",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2100
        },
        {
          "frame": "frames/multi-agent-workbench/10.png",
          "caption": "The stream is only the view; the manifest, job ledger, trace, and artifact versions are the record",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2800
        }
      ]
    },
    {
      "id": "startup-diligence-war-room",
      "title": "Startup diligence war-room package",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/startup-diligence-war-room/01.png",
          "caption": "Blank room, not blank agent: the startup-banking room already has sheet, notes, wall, Copilot, and trace",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 1800
        },
        {
          "frame": "frames/startup-diligence-war-room/02.png",
          "caption": "Open the company research sheet",
          "cursor": {
            "x": 460,
            "y": 94
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/startup-diligence-war-room/03.png",
          "caption": "This is the shared queue for CardioNova intake, batch diligence, source refs, and owner review",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1700
        },
        {
          "frame": "frames/startup-diligence-war-room/04.png",
          "caption": "Run source-backed enrichment for the startup-banking watchlist",
          "cursor": {
            "x": 289,
            "y": 190
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/startup-diligence-war-room/05.png",
          "caption": "Rows move to complete with summaries, signals, source links, and freshness",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 3300
        },
        {
          "frame": "frames/startup-diligence-war-room/06.png",
          "caption": "Use the public room lane for shared analyst work across multiple agents",
          "cursor": {
            "x": 1073,
            "y": 573
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/startup-diligence-war-room/07.png",
          "caption": "Use the public room lane for shared analyst work across multiple agents",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 950
        },
        {
          "frame": "frames/startup-diligence-war-room/08.png",
          "caption": "One burst prompt becomes concurrent research, finance, review, and handoff lanes",
          "cursor": {
            "x": 1073,
            "y": 573
          },
          "click": false,
          "kind": "action",
          "holdMs": 800
        },
        {
          "frame": "frames/startup-diligence-war-room/09.png",
          "caption": "One burst prompt becomes concurrent research, finance, review, and handoff lanes",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 520
        },
        {
          "frame": "frames/startup-diligence-war-room/10.png",
          "caption": "One burst prompt becomes concurrent research, finance, review, and handoff lanes",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 1300
        },
        {
          "frame": "frames/startup-diligence-war-room/11.png",
          "caption": "The work queue is now startup-specific: CardioNova, bulk rows, runway chart, and protected edits",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2100
        },
        {
          "frame": "frames/startup-diligence-war-room/12.png",
          "caption": "The package seals only after source checks, runway assumptions, and no-clobber proof agree",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2100
        },
        {
          "frame": "frames/startup-diligence-war-room/13.png",
          "caption": "Pause on the proof board: cited cells, chart assumptions, human edit preservation, and draft-only handoff are visible",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 5000
        },
        {
          "frame": "frames/startup-diligence-war-room/14.png",
          "caption": "Switch to the private NodeAgent lane",
          "cursor": {
            "x": 1208,
            "y": 96
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/startup-diligence-war-room/15.png",
          "caption": "The active Private tab is highlighted: work stays owner-scoped until promoted",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2600
        },
        {
          "frame": "frames/startup-diligence-war-room/16.png",
          "caption": "Ask for private banker judgment without publishing it to the room",
          "cursor": {
            "x": 1073,
            "y": 661
          },
          "click": false,
          "kind": "action",
          "holdMs": 800
        },
        {
          "frame": "frames/startup-diligence-war-room/17.png",
          "caption": "Ask for private banker judgment without publishing it to the room",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 520
        },
        {
          "frame": "frames/startup-diligence-war-room/18.png",
          "caption": "Ask for private banker judgment without publishing it to the room",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 1300
        },
        {
          "frame": "frames/startup-diligence-war-room/19.png",
          "caption": "The owner lane shows the private ask; nothing is promoted to the room",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1800
        },
        {
          "frame": "frames/startup-diligence-war-room/20.png",
          "caption": "Downstream actions are approval-gated drafts, not silent OAuth sends",
          "cursor": {
            "x": 440,
            "y": 243
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/startup-diligence-war-room/21.png",
          "caption": "The visible promise is honest: package Gmail, Notion, Slack, Linear, LinkedIn, and CRM drafts; a human approves",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2200
        }
      ]
    },
    {
      "id": "research-upsert",
      "title": "GTM research import — updates, never duplicates",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/research-upsert/01.png",
          "caption": "A GTM research sheet — statuses run like a CRM pipeline",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2000
        },
        {
          "frame": "frames/research-upsert/02.png",
          "caption": "Import accounts — paste like a CRM",
          "cursor": {
            "x": 1165,
            "y": 144
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/research-upsert/03.png",
          "caption": "Import accounts — paste like a CRM",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 950
        },
        {
          "frame": "frames/research-upsert/04.png",
          "caption": "Paste company, website, tier, intent, owner…",
          "cursor": {
            "x": 839,
            "y": 270
          },
          "click": false,
          "kind": "action",
          "holdMs": 800
        },
        {
          "frame": "frames/research-upsert/05.png",
          "caption": "Paste company, website, tier, intent, owner…",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 1300
        },
        {
          "frame": "frames/research-upsert/06.png",
          "caption": "One click to import",
          "cursor": {
            "x": 1160,
            "y": 270
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/research-upsert/07.png",
          "caption": "New row lands — pending, ready to enrich",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1700
        },
        {
          "frame": "frames/research-upsert/08.png",
          "caption": "Re-import the same account…",
          "cursor": {
            "x": 1165,
            "y": 144
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/research-upsert/09.png",
          "caption": "Re-import the same account…",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 950
        },
        {
          "frame": "frames/research-upsert/10.png",
          "caption": "Same company, new owner",
          "cursor": {
            "x": 839,
            "y": 270
          },
          "click": false,
          "kind": "action",
          "holdMs": 800
        },
        {
          "frame": "frames/research-upsert/11.png",
          "caption": "Same company, new owner",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 1300
        },
        {
          "frame": "frames/research-upsert/12.png",
          "caption": "Import again",
          "cursor": {
            "x": 1160,
            "y": 270
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/research-upsert/13.png",
          "caption": "The existing row UPDATES — no duplicate, sourced research preserved",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1700
        },
        {
          "frame": "frames/research-upsert/14.png",
          "caption": "Still 4 accounts — re-import = update, never a duplicate (CRM convention)",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2400
        }
      ]
    },
    {
      "id": "first-time-banker-capture",
      "title": "First-time banker happy path — join, note, notice, choose",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/first-time-banker-capture/01.png",
          "caption": "Join the room — land on the Notebook. Placeholder says what to jot.",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2200
        },
        {
          "frame": "frames/first-time-banker-capture/02.png",
          "caption": "Jot what you heard — no structure needed yet",
          "cursor": {
            "x": 524,
            "y": 203
          },
          "click": false,
          "kind": "action",
          "holdMs": 800
        },
        {
          "frame": "frames/first-time-banker-capture/03.png",
          "caption": "Jot what you heard — no structure needed yet",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 520
        },
        {
          "frame": "frames/first-time-banker-capture/04.png",
          "caption": "Jot what you heard — no structure needed yet",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 1300
        },
        {
          "frame": "frames/first-time-banker-capture/05.png",
          "caption": "Save the note — the notebook commits on blur",
          "cursor": {
            "x": 1073,
            "y": 573
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/first-time-banker-capture/06.png",
          "caption": "Saved. Now pause and let the room notice what's worth returning to.",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1500
        },
        {
          "frame": "frames/first-time-banker-capture/07.png",
          "caption": "The room is watching. NodeRoom noticed signals in your notes.",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 3200
        },
        {
          "frame": "frames/first-time-banker-capture/08.png",
          "caption": "NodeRoom noticed — chip surfaces when there is something worth returning to",
          "cursor": null,
          "click": false,
          "kind": "loading",
          "holdMs": 1600
        },
        {
          "frame": "frames/first-time-banker-capture/09.png",
          "caption": "Click to open the room intelligence inbox",
          "cursor": {
            "x": 1175,
            "y": 769
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/first-time-banker-capture/10.png",
          "caption": "CardioNova flagged: funding, runway, and hospital signals",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2000
        },
        {
          "frame": "frames/first-time-banker-capture/11.png",
          "caption": "Click Research — you chose what to do with it",
          "cursor": {
            "x": 921,
            "y": 719
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/first-time-banker-capture/12.png",
          "caption": "Researching. Suggest, don't automate: you're still in control.",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2400
        },
        {
          "frame": "frames/first-time-banker-capture/13.png",
          "caption": "30 seconds: note → notice → choose. The room captured your intent.",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 3000
        }
      ]
    },
    {
      "id": "review-approve",
      "title": "Review mode — approve agent edits at the cell",
      "skipped": false,
      "segments": [
        {
          "frame": "frames/review-approve/01.png",
          "caption": "Don't trust the agent yet? Flip off auto-allow",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 1800
        },
        {
          "frame": "frames/review-approve/02.png",
          "caption": "Review mode ON — agents must propose, not write",
          "cursor": {
            "x": 1020,
            "y": 29
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/review-approve/03.png",
          "caption": "Review mode ON — agents must propose, not write",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 950
        },
        {
          "frame": "frames/review-approve/04.png",
          "caption": "Same ask — but now every edit needs your sign-off",
          "cursor": {
            "x": 275,
            "y": 690
          },
          "click": false,
          "kind": "action",
          "holdMs": 800
        },
        {
          "frame": "frames/review-approve/05.png",
          "caption": "Same ask — but now every edit needs your sign-off",
          "cursor": null,
          "click": false,
          "kind": "typed",
          "holdMs": 1300
        },
        {
          "frame": "frames/review-approve/06.png",
          "caption": "The agent works — but writes become proposals",
          "cursor": null,
          "click": false,
          "kind": "loading",
          "holdMs": 1600
        },
        {
          "frame": "frames/review-approve/07.png",
          "caption": "Proposals appear ON the cells — like suggestions in Docs",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 2100
        },
        {
          "frame": "frames/review-approve/08.png",
          "caption": "Approve right where the change lands",
          "cursor": {
            "x": 1130,
            "y": 254
          },
          "click": true,
          "kind": "action",
          "holdMs": 950
        },
        {
          "frame": "frames/review-approve/09.png",
          "caption": "Applied via the same no-clobber CAS path — synced to everyone",
          "cursor": null,
          "click": false,
          "kind": "result",
          "holdMs": 1700
        },
        {
          "frame": "frames/review-approve/10.png",
          "caption": "Human-in-the-loop, one click, in context",
          "cursor": null,
          "click": false,
          "kind": "state",
          "holdMs": 2400
        }
      ]
    }
  ]
};
