/**
 * Episode assembler — turns an episode's storyboard + voiceover timings + ready-scene MP4s into
 * `remotion/episode.data.js` (consumed by remotion/Episode.tsx) and stages the assets into
 * remotion/public/{audio,video}. Staged scenes (no captures yet) render as styled cards — honest
 * interim treatment: real narration over real claims, no fake app footage.
 *
 * Run:  npx tsx scripts/walkthroughs/episode.ts noderoom-live-collab-v1
 * Then: npx remotion render remotion/index.ts episode-short episodes/<id>/renders/short.mp4 --codec=h264
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const FPS = 30;
const episodeId = process.argv[2] ?? "noderoom-live-collab-v1";
const epDir = join(ROOT, "episodes", episodeId);

type SceneIn = { id: string; type: string; status: string; narration: string; source?: string };
function parseScenes(yaml: string): SceneIn[] {
  const out: SceneIn[] = [];
  let cur: SceneIn | null = null;
  for (const line of yaml.split(/\r?\n/)) {
    const id = line.match(/^\s+-\s+id:\s*(\S+)/);
    if (id) { cur = { id: id[1], type: "", status: "ready", narration: "" }; out.push(cur); continue; }
    if (!cur) continue;
    const t = line.match(/^\s+type:\s*(\S+)/); if (t) cur.type = t[1];
    const st = line.match(/^\s+status:\s*(\w+)/); if (st) cur.status = st[1];
    const n = line.match(/^\s+narration:\s*"(.+)"\s*$/); if (n) cur.narration = n[1];
    const s = line.match(/^\s+source:\s*(\S+)/); if (s) cur.source = s[1];
  }
  return out;
}

// Card content for staged scenes — the honest interim treatment (claims, not fake footage).
const CARDS: Record<string, { title: string; bullets: string[] }> = {
  "naive-problem": { title: "The naive demo breaks", bullets: ["Human edits a cell", "Agent writes a stale value", "Silent overwrite — nobody sees it"] },
  "code-before-after": { title: "convex/artifacts.ts — applyCellEditCore", bullets: ["affected-range LOCK gate", "per-element VERSION check (CAS)", "draft / proposal on conflict — never clobber"] },
  "mental-model": { title: "The room is the product", bullets: ["lock → draft → smart merge", "proposal review at the cell", "every edit traced + versioned"] },
  "closing-thesis": { title: "Agents are leaving the chatbox", bullets: ["Shared work surfaces need versions, locks, review", "This video was rendered from the repo that proves it"] },
};

const run = () => {
  const scenes = parseScenes(readFileSync(join(epDir, "storyboard.yaml"), "utf8"));
  const timings = JSON.parse(readFileSync(join(epDir, "voiceover", "timings.json"), "utf8")) as Record<string, { narrationSec: number }>;
  mkdirSync(join(ROOT, "remotion", "public", "audio"), { recursive: true });
  mkdirSync(join(ROOT, "remotion", "public", "video"), { recursive: true });

  const out = [];
  for (const s of scenes) {
    if (!s.narration) continue;
    const nar = timings[s.id]?.narrationSec ?? 4;
    // visual must outlast narration (+1.2s breath); video scenes get a bit more room to read
    const durSec = Math.max(nar + 1.2, s.source ? Math.min(nar + 4.5, 11) : nar + 1.6);
    const mp3 = join(epDir, "voiceover", `${s.id}.mp3`);
    let audio: string | null = null;
    if (existsSync(mp3)) { copyFileSync(mp3, join(ROOT, "remotion", "public", "audio", `${s.id}.mp3`)); audio = `audio/${s.id}.mp3`; }
    let video: string | null = null;
    if (s.source && s.status === "ready") {
      const src = join(ROOT, s.source);
      if (existsSync(src)) { copyFileSync(src, join(ROOT, "remotion", "public", "video", `${s.id}.mp4`)); video = `video/${s.id}.mp4`; }
      else console.warn(`[episode] MISSING source for ready scene ${s.id}: ${s.source}`);
    }
    out.push({
      id: s.id, kind: video ? "video" : "card", video, audio,
      durationInFrames: Math.round(durSec * FPS),
      narration: s.narration,
      card: CARDS[s.id] ?? { title: s.id, bullets: [] },
    });
  }
  const total = out.reduce((a, s) => a + s.durationInFrames, 0);
  const data = { episodeId, fps: FPS, title: "I Tried to Make a Demo GIF for a Spreadsheet Agent. It Turned Into a Multiplayer AI Workspace.", scenes: out, totalFrames: total };
  writeFileSync(join(ROOT, "remotion", "episode.data.js"), `// AUTO-GENERATED by scripts/walkthroughs/episode.ts\nexport default ${JSON.stringify(data, null, 2)};\n`);
  console.log(`[episode] ${out.length} scenes · ${(total / FPS).toFixed(1)}s total → remotion/episode.data.js`);
};
run();
